name: Build
on:
  push:
    branches:
      - main
    path-ignores:
      - sonar_report.json
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          ref: ${{ github.head_ref }}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@dcc5211de53084482f1c6779dda263459f5274f6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Fetch Sonar Issues
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -s -u $SONAR_TOKEN: \
          "https://sonarcloud.io/api/issues/search?componentKeys=mridulgohain-triedatum_jil2airflow&pullRequest=${PR_NUMBER}" | jq '.' > sonar_issues.json
      #- name: Upload Sonar report
        #uses: actions/upload-artifact@v4
        #with:
          #name: sonar-issues-report
          #path: sonar_issues.json
      - name: Add sonar report to repository
        env: 
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          git config  user.name "mridulgohain-triedatum"
          git config  user.email "mridul.gohain@triedatum.com"

          git add sonar_issues.json
          git diff --staged --quiet || git commit -m "Update Sonar report"

          git push origin HEAD:$BRANCH_NAME
          
        
      